export const NUMBERS: Record<string, string> = {
  0: "null",
  1: "eins",
  2: "zwei",
  3: "drei",
  4: "vier",
  5: "fünf",
  6: "sechs",
  7: "sieben",
  8: "acht",
  9: "neun",
  10: "zehn",
  11: "elf",
  12: "zwölf",
  "30-": "ßig",
  "0-": "zig",
  "6-": "sech",
  "7-": "sieb",
};
