import { Article, ArticleType, Case, Gender } from "@/types";

export const ARTICLES: Article[] = [
  // der, die, das
  {
    spell: "der",
    type: ArticleType.Definite,
    case: Case.Nominativ,
    gender: Gender.Masculine,
    tags: [],
  },
  {
    spell: "den",
    type: ArticleType.Definite,
    case: Case.Akkusativ,
    gender: Gender.Masculine,
    tags: [],
  },
  {
    spell: "dem",
    type: ArticleType.Definite,
    case: Case.Dativ,
    gender: Gender.Masculine,
    tags: [],
  },
  {
    spell: "des",
    type: ArticleType.Definite,
    case: Case.Genitiv,
    gender: Gender.Masculine,
    tags: [],
  },
  {
    spell: "die",
    type: ArticleType.Definite,
    case: Case.Nominativ,
    gender: Gender.Feminine,
    tags: [],
  },
  {
    spell: "die",
    type: ArticleType.Definite,
    case: Case.Akkusativ,
    gender: Gender.Feminine,
    tags: [],
  },
  {
    spell: "der",
    type: ArticleType.Definite,
    case: Case.Dativ,
    gender: Gender.Feminine,
    tags: [],
  },
  {
    spell: "der",
    type: ArticleType.Definite,
    case: Case.Genitiv,
    gender: Gender.Feminine,
    tags: [],
  },
  {
    spell: "das",
    type: ArticleType.Definite,
    case: Case.Nominativ,
    gender: Gender.Neutral,
    tags: [],
  },
  {
    spell: "das",
    type: ArticleType.Definite,
    case: Case.Akkusativ,
    gender: Gender.Neutral,
    tags: [],
  },
  {
    spell: "dem",
    type: ArticleType.Definite,
    case: Case.Dativ,
    gender: Gender.Neutral,
    tags: [],
  },
  {
    spell: "des",
    type: ArticleType.Definite,
    case: Case.Genitiv,
    gender: Gender.Neutral,
    tags: [],
  },
  // ein
  {
    spell: "ein",
    type: ArticleType.Indefinite,
    case: Case.Nominativ,
    gender: Gender.Masculine,
    tags: [],
  },
  {
    spell: "einen",
    type: ArticleType.Indefinite,
    case: Case.Akkusativ,
    gender: Gender.Masculine,
    tags: [],
  },
  {
    spell: "einem",
    type: ArticleType.Indefinite,
    case: Case.Dativ,
    gender: Gender.Masculine,
    tags: [],
  },
  {
    spell: "eines",
    type: ArticleType.Indefinite,
    case: Case.Genitiv,
    gender: Gender.Masculine,
    tags: [],
  },
  {
    spell: "eine",
    type: ArticleType.Indefinite,
    case: Case.Nominativ,
    gender: Gender.Feminine,
    tags: [],
  },
  {
    spell: "eine",
    type: ArticleType.Indefinite,
    case: Case.Akkusativ,
    gender: Gender.Feminine,
    tags: [],
  },
  {
    spell: "einer",
    type: ArticleType.Indefinite,
    case: Case.Dativ,
    gender: Gender.Feminine,
    tags: [],
  },
  {
    spell: "einer",
    type: ArticleType.Indefinite,
    case: Case.Genitiv,
    gender: Gender.Feminine,
    tags: [],
  },
  {
    spell: "ein",
    type: ArticleType.Indefinite,
    case: Case.Nominativ,
    gender: Gender.Neutral,
    tags: [],
  },
  {
    spell: "ein",
    type: ArticleType.Indefinite,
    case: Case.Akkusativ,
    gender: Gender.Neutral,
    tags: [],
  },
  {
    spell: "einem",
    type: ArticleType.Indefinite,
    case: Case.Dativ,
    gender: Gender.Neutral,
    tags: [],
  },
  {
    spell: "eines",
    type: ArticleType.Indefinite,
    case: Case.Genitiv,
    gender: Gender.Neutral,
    tags: [],
  },
  // kein
  {
    spell: "kein",
    type: ArticleType.Negative,
    case: Case.Nominativ,
    gender: Gender.Masculine,
    tags: [],
  },
  {
    spell: "keinen",
    type: ArticleType.Negative,
    case: Case.Akkusativ,
    gender: Gender.Masculine,
    tags: [],
  },
  {
    spell: "keinem",
    type: ArticleType.Negative,
    case: Case.Dativ,
    gender: Gender.Masculine,
    tags: [],
  },
  {
    spell: "keines",
    type: ArticleType.Negative,
    case: Case.Genitiv,
    gender: Gender.Masculine,
    tags: [],
  },
  {
    spell: "keine",
    type: ArticleType.Negative,
    case: Case.Nominativ,
    gender: Gender.Feminine,
    tags: [],
  },
  {
    spell: "keine",
    type: ArticleType.Negative,
    case: Case.Akkusativ,
    gender: Gender.Feminine,
    tags: [],
  },
  {
    spell: "keiner",
    type: ArticleType.Negative,
    case: Case.Dativ,
    gender: Gender.Feminine,
    tags: [],
  },
  {
    spell: "keiner",
    type: ArticleType.Negative,
    case: Case.Genitiv,
    gender: Gender.Feminine,
    tags: [],
  },
  {
    spell: "kein",
    type: ArticleType.Negative,
    case: Case.Nominativ,
    gender: Gender.Neutral,
    tags: [],
  },
  {
    spell: "kein",
    type: ArticleType.Negative,
    case: Case.Akkusativ,
    gender: Gender.Neutral,
    tags: [],
  },
  {
    spell: "keinem",
    type: ArticleType.Negative,
    case: Case.Dativ,
    gender: Gender.Neutral,
    tags: [],
  },
  {
    spell: "keines",
    type: ArticleType.Negative,
    case: Case.Genitiv,
    gender: Gender.Neutral,
    tags: [],
  },
  // dies
  {
    spell: "dieser",
    type: ArticleType.Demonstrative,
    case: Case.Nominativ,
    gender: Gender.Masculine,
    tags: [],
  },
  {
    spell: "diesen",
    type: ArticleType.Demonstrative,
    case: Case.Akkusativ,
    gender: Gender.Masculine,
    tags: [],
  },
  {
    spell: "diesem",
    type: ArticleType.Demonstrative,
    case: Case.Dativ,
    gender: Gender.Masculine,
    tags: [],
  },
  {
    spell: "dieses",
    type: ArticleType.Demonstrative,
    case: Case.Genitiv,
    gender: Gender.Masculine,
    tags: [],
  },
  {
    spell: "diese",
    type: ArticleType.Demonstrative,
    case: Case.Nominativ,
    gender: Gender.Feminine,
    tags: [],
  },
  {
    spell: "diese",
    type: ArticleType.Demonstrative,
    case: Case.Akkusativ,
    gender: Gender.Feminine,
    tags: [],
  },
  {
    spell: "dieser",
    type: ArticleType.Demonstrative,
    case: Case.Dativ,
    gender: Gender.Feminine,
    tags: [],
  },
  {
    spell: "dieser",
    type: ArticleType.Demonstrative,
    case: Case.Genitiv,
    gender: Gender.Feminine,
    tags: [],
  },
  {
    spell: "dieses",
    type: ArticleType.Demonstrative,
    case: Case.Nominativ,
    gender: Gender.Neutral,
    tags: [],
  },
  {
    spell: "dieses",
    type: ArticleType.Demonstrative,
    case: Case.Akkusativ,
    gender: Gender.Neutral,
    tags: [],
  },
  {
    spell: "diesem",
    type: ArticleType.Demonstrative,
    case: Case.Dativ,
    gender: Gender.Neutral,
    tags: [],
  },
  {
    spell: "dieses",
    type: ArticleType.Demonstrative,
    case: Case.Genitiv,
    gender: Gender.Neutral,
    tags: [],
  },
];

export const ARTICLE_WORDS_MAP = {
  [ArticleType.Definite]: "d-",
  [ArticleType.Indefinite]: "ein-",
  [ArticleType.Negative]: "kein-",
  [ArticleType.Demonstrative]: "dies-",
  tags: [],
};
