import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NAVIGATION_ITEMS = [
  { name: "Basic Article", href: "/basic-article" },
  { name: "Article in Sentence", href: "/article-in-sentence" },
  { name: "Number Listening", href: "/number-listening" },
  { name: "Number Reading", href: "/number-reading" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"asfd"}>
        <div className="main container mx-auto flex gap-10">
          <nav className="divide-y md:w-60">
            {NAVIGATION_ITEMS.map(({ name, href }) => (
              <Link key={name} className="block" href={href}>
                <div className="px-5 py-3 ">{name}</div>
              </Link>
            ))}
          </nav>
          <div className="grow">{children}</div>
        </div>
      </body>
    </html>
  );
}
